# Generated by Django 2.2.7 on 2020-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0002_auto_20171003_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(choices=[('email', 'email')], max_length=100, verbose_name='medium'),
        ),
    ]
